### ISSUE TITLE
Ansible related questions

### ISSUE THREAD

**Issue by cassioac** [nemesisdesign/ansible-openwisp2#4]
Hi, thanks for this new interface, the ruby one gave me headaches :)

I'm new to ansible and am having a hard time to understand how it works.

If I understood correctly, I have to deploy the server every time it restarts, is that correct?

If so, is there a way to deploy a server permanently, so it resists restarts?

What's the correct way to have a production server running with your software?

Regards!

Cassio

**Comment by cassioac** [comment]
Also, is there a way to retrieve current AP configuration in RAW json format, to serve as model to others?

**Comment by nemesisdesign** [comment]
This is a bug tracker and we should use it to report bugs. For future questions please use the [OpenWISP mailing list](https://groups.google.com/forum/#!forum/openwisp).

You do not have to deploy every time the server restarts. You deploy once and then upgrade periodically, if you want. The correct way to have a production server is to carefully follow all the steps provided in the README of this repo, if anything doesn't work out for you just let me know.
